name: Deploy to AWS ECR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 3: Debug AWS Credentials (Optional)
      - name: Verify AWS Credentials
        run: |
          aws sts get-caller-identity || echo "Invalid AWS credentials"

      # Step 4: Ensure ECR Repositories Exist
      - name: Ensure ECR Repositories Exist
        run: |
          aws ecr describe-repositories --repository-names myapp-repo || aws ecr create-repository --repository-name myapp-repo
          aws ecr describe-repositories --repository-names mysql-repo || aws ecr create-repository --repository-name mysql-repo

      # Step 5: Login to Amazon ECR
      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 069408709901.dkr.ecr.us-east-1.amazonaws.com

      # Step 6: Build and Push Web Application Image
      - name: Build and Push Web Application Image
        env:
          ECR_REGISTRY: 069408709901.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: myapp-repo
          IMAGE_TAG: app-v0.1
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      # Step 7: Build and Push MySQL Image
      - name: Build and Push MySQL Image
        env:
          ECR_REGISTRY: 069408709901.dkr.ecr.us-east-1.amazonaws.com
          ECR_REPOSITORY: mysql-repo
          IMAGE_TAG: mysql-v0.1
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile_mysql .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
